name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build aplikacije
    runs-on: ubuntu-latest
    
    steps:
    - name: Prenesi kodo
      uses: actions/checkout@v4
      
    - name: Nastavi .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Obnovi odvisnosti
      run: dotnet restore City-Feedback/City-Feedback.csproj
      
    - name: Build aplikacije
      run: dotnet build City-Feedback/City-Feedback.csproj --configuration Release --no-restore
      
    - name: Objavi aplikacijo
      run: dotnet publish City-Feedback/City-Feedback.csproj --configuration Release --no-build --output ./publish
      
    - name: Naloži artefakte
      uses: actions/upload-artifact@v4
      with:
        name: city-feedback-app
        path: ./publish
        retention-days: 7
