name: Deploy to Azure Web App (CityFeedback)

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Prenesi kodo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Neposredni deploy iz Publish Profile (brez prijave s client-id)
      - name: Deploy to Azure Web App using publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedbackdev'                  # točno ime Web App v Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'lovro005/cityfeedback:latest'    # tvoja Docker Hub slika
