name: CI/CD CityFeedback

permissions:
  contents: read

on:
  push:
    branches: [ main, development ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./City-Feedback
          file: ./City-Feedback/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}

  deploy-prod:
    needs: docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PROD
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedback-prod'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}'