name: CI/CD CityFeedback

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main, development ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore City-Feedback/City-Feedback.sln
      - run: dotnet build City-Feedback/City-Feedback.sln --configuration Release --no-restore
      - run: dotnet test City-Feedback.Tests/City-Feedback.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: MSTest Results
          path: '**/test-results.trx'
          reporter: dotnet-trx

  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./City-Feedback
          file: ./City-Feedback/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}

  deploy-test:
    needs: docker
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy TEST
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedback-test'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}'

  deploy-prod:
    needs: docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PROD
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedback'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}'
