name: CI/CD CityFeedback

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: ./City-Feedback
        run: dotnet restore

      - name: Build
        working-directory: ./City-Feedback
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ./City-Feedback.Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/test-results.trx'

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: MSTest Results
          path: '**/test-results.trx'
          reporter: dotnet-trx
          fail-on-error: true


  docker:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./City-Feedback
          file: ./City-Feedback/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}


  deploy-test:
    needs: docker
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to TEST Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedback-test'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}'


  deploy-prod:
    needs: docker
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cityfeedback'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/cityfeedback:${{ github.sha }}'
